### PR TITLE
Added support for config created with next-compose-plugins

### PR DESCRIPTION
**Pull request by matobeno1**
Hi there, I'm trying to integrate your package to a project I'm working on. We're using the [next-compose-plugins](https://www.npmjs.com/package/next-compose-plugins) and it seems that the package doesn't support it, so I created this
pull request that adds the desired functionality. I just matched the required api for it to work successfully.

I tried to run the included tests, but they fail at my machine, even on master branch without the new changes. When used on my project, it works as expected.

If there's something else I missed, please let me know :)

### CODE REVIEW

**Comment by Niels-IO** [comment]
Hi @matobeno1,

Thanks a lot for your contribution! I will have a look at it in the coming days 🙂

Cheers 
Niels

**Comment by Niels-IO** [comment]
Hi @matobeno1,

Thanks a lot! I merged your PR and published v0.8.0

For me, the tests did run successfully. Could you please share the error that you received?

**Comment by matobeno1** [comment]
> Hi @matobeno1,
> 
> Thanks a lot! I merged your PR and published v0.8.0
> 
> For me, the tests did run successfully. Could you please share the error that you received?

@Niels-IO Thank you for the merge and effort with the module!

This was run on `master` with `npm test` and fresh modules install. I didn't really dig into it, sorry.
I am using MacBook Air (M1, 2020):
```
> next-image-export-optimizer@0.7.2 test
> jest

 FAIL  test/optimizeImages.test.js (18.146 s)
  ✕ Optimize images (18054 ms)

  ● Optimize images

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `Optimize images 5`

    - Snapshot  - 15
    + Received  + 15

      Array [
    -   40418,
    -   45568,
    -   2352,
    +   40250,
    +   45584,
    +   2338,
        136,
    -   85030,
    -   93140,
    -   5906,
    -   342,
    -   10304,
    -   219286,
    -   578,
    -   882,
    -   19842,
    -   25324,
    -   28758,
    -   1514,
    +   84746,
    +   93116,
    +   5944,
    +   338,
    +   10326,
    +   219028,
    +   582,
    +   864,
    +   19852,
    +   25344,
    +   28734,
    +   1504,
      ]

      154 |     }
      155 |     if (index == 0) {
    > 156 |       expect(imageFileStats).toMatchInlineSnapshot(`
          |                              ^
      157 |   Array [
      158 |     40418,
      159 |     45568,

      at Object.<anonymous> (test/optimizeImages.test.js:156:30)

  ● Optimize images

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `Optimize images 6`

    - Snapshot  - 16
    + Received  + 16

      Array [
    -   107646,
    -   121736,
    -   6478,
    -   282,
    -   242404,
    -   270090,
    -   15934,
    -   806,
    -   26660,
    -   866440,
    -   1512,
    -   2462,
    -   52038,
    -   63662,
    -   74588,
    -   4448,
    +   107796,
    +   122246,
    +   6466,
    +   288,
    +   243172,
    +   270284,
    +   15916,
    +   804,
    +   26670,
    +   865700,
    +   1524,
    +   2454,
    +   51958,
    +   63890,
    +   75022,
    +   4428,
      ]

      175 |   `);
      176 |     } else if (index === 1) {
    > 177 |       expect(imageFileStats).toMatchInlineSnapshot(`
          |                              ^
      178 | Array [
      179 |   107646,
      180 |   121736,

      at Object.<anonymous> (test/optimizeImages.test.js:177:30)

 › 2 snapshots failed.
Snapshot Summary
 › 2 snapshots failed from 1 test suite. Inspect your code changes or run `npm test -- -u` to update them.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   2 failed, 4 passed, 6 total
Time:        18.165 s, estimated 19 s
Ran all test suites.

Process finished with exit code 1
```

The playwright tests passed, problem was on my end.

**Comment by Niels-IO** [comment]
Interesting! I think it has to do with the resolved sharp version. Slightly different image sizes that then didn't match up with the sizes in the snapshot.

**Pull request merged**
