### PR TITLE
Adding support for monorepos

### PR DESCRIPTION
**Pull request by stefangoor**
These changes came about from issues I was having using the module in an Nx mororepo. 

1. The script expected the Next.js project to be in the current directory, not in subdirectories, so I updated the script to take an optional parameter to specify the location of the next.config.js file.
2. The parameters in the next.config.js were integers and booleans, but my Next.js project was giving lint errors and compile errors complaining that strings were expected, so I updated the script to handle the parameters as either integer or string for the quality setting and either a string or boolean for the WebP and blur settings.

I have attempted to make these changes backwards compatible and seamless so this should not affect people using the current version of the scripts.

### CODE REVIEW

**Comment by Niels-IO** [comment]
Hi @stefangoor,

Thanks for your contribution! I will have a look at the implementation. 
Regarding the second point, I have a question: Was the error originating from typescript? I had to declare in a file called environment.d.ts the types of the env vars in order for it to understand these types:
```typescript

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      nextImageExportOptimizer_storePicturesInWEBP: boolean;
      nextImageExportOptimizer_generateAndUseBlurImages: boolean;
    }
  }
}

// If this file has no import/export statements (i.e., is a script)
// convert it into a module by adding an empty export statement.
export {};
```

If such a file eliminated the errors you mentioned, I would enforce the correct types in the next.config.js rather than support both booleans and strings.

**Comment by stefangoor** [comment]
Hi Niels,

Thanks for that.  I'm happy to change the PR if there is a better way to get the types of parameters handled so that the nextjs project compiles and the image script works correctly.

Yes, the issue error originated from TypeScript.  My next.config.js looks like this:

```
//@ts-check

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { withNx } = require('@nrwl/next/plugins/with-nx');

/**json
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
  images: {
    loader: "custom",
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
  },
  env: {
    nextImageExportOptimizer_imageFolderPath: "apps/web-nextjs/public/images",
    nextImageExportOptimizer_exportFolderPath: "dist/apps/web-nextjs/exported",
    nextImageExportOptimizer_quality: "75",
    nextImageExportOptimizer_storePicturesInWEBP: "false",
    nextImageExportOptimizer_generateAndUseBlurImages: "true",
  },
  exportPathMap: async function (
    defaultPathMap,
    { dev, dir, outDir, distDir, buildId }
  ) {
    return {
      '/': { page: '/' },
    }
  },
};

module.exports = withNx(nextConfig);
```

If I change the nextImageExportOptimizer_quality to an Integer, both the linter and project build give the following error:

```
Type error: Type 'number' is not assignable to type 'string'.

  23 |     nextImageExportOptimizer_imageFolderPath: "apps/web-nextjs/public/images",
  24 |     nextImageExportOptimizer_exportFolderPath: "dist/apps/web-nextjs/exported",
> 25 |     nextImageExportOptimizer_quality: 75,
     |     ^
  26 |     nextImageExportOptimizer_storePicturesInWEBP: false,
  27 |     nextImageExportOptimizer_generateAndUseBlurImages: true,
  28 |   },
```

Similarly, if the nextImageExportOptimizer_storePicturesInWEBP is not a string then I get the following error:

```
Type error: Type 'boolean' is not assignable to type 'string'.

  24 |     nextImageExportOptimizer_exportFolderPath: "dist/apps/web-nextjs/exported",
  25 |     nextImageExportOptimizer_quality: "75",
> 26 |     nextImageExportOptimizer_storePicturesInWEBP: false,
     |     ^
  27 |     nextImageExportOptimizer_generateAndUseBlurImages: true,
  28 |   },
  29 |   exportPathMap: async function (
```

I'm not sure exactly what you mean with the environment.d.ts, I see it in the node_module, but I still get the build error.  Do I need to add that to my tsconfig.json to get that picked up?

Thanks,
Stefan

**Comment by Niels-IO** [comment]
Hi @stefangoor,
The use of the environment.d.ts is explained here in a good way: https://stackoverflow.com/a/53981706/17515424

But I think these TS errors come from the fact that TS checks next.config.js. Would it be enough to remove the ts-check at the beginning of your file?

**Comment by stefangoor** [comment]
Hi Niels,

Thanks for the response.  Yes you are right, by default we type check everything but I think it makes sense to exclude the next.config.js as it will have content from several plugins and modules.

When I remove the tscheck it compiles correctly so I will update the PR shortly to remove the changes related to the types.

Thanks again,
Stefan

**Comment by stefangoor** [comment]
@Niels-IO sorry for the delay on this but I have updated the PR now to remove the type changes on the parameters.  It just has the support for the custom next config file now.  Please let me know if you have any questions.  Thanks

**Comment by Niels-IO** [comment]
Hi @stefangoor,

Thank you very much for your PR. I only made a minor change: Test for the existence of the public folder and not the imageFolder.

**Pull request merged**
