### PR TITLE
Enable setting of custom headers in remoteOptimizedImages.js

### PR DESCRIPTION
**Pull request by Niels-IO**

### CODE REVIEW

**Comment by mmarseu** [comment]
Thank you for this.
It seems to work as advertised. Unfortunately it turns out this is only a partial solution to my problem. 
I wasn't aware of this until I tested your solution but apparently the server also blocks HTTP/1.1 connections. When I request the same image using the same headers with HTTP/2, it works. 

I'm not sure that you consider this within scope of your package. If you do, I'll write another issue for this.

As a workaround, would it also be possible that I fetch the images manually in another script and provide them to your package for processing?

**Comment by Niels-IO** [comment]
Hi @mmarseu,
I am hesitant to switch to Node.js http2 library. I fear that, in turn, not all servers would accept a http2 request.

**Comment by mmarseu** [comment]
I'm sure that's true and since I'm hardly an expert on network protocols, I can't provide any suggestions.

So given that in any case I have to provide image URLs in `remoteOptimizedImages.js`, I might as well fetch them myself, using any technology at my disposal and provide them to your tool for processing. This would be a convenient workaround for me and all similar cases, I'd say.
Is that already supported?

**Comment by Niels-IO** [comment]
Hi @mmarseu, if the URL that you return from remoteOptimizedImages.js is a normal https URL, then yes. If it is a file URL, then the downloadImage function needs this functionality added.

**Comment by mmarseu** [comment]
I'm sorry, I don't quite follow.
The case when the URL is a "normal HTTPS URL" is what isn't working for me. Because the requests generated by your tool are rejected by the server.
I understand from your comment that I can't return file:// URLs because that's not supported.

Is there a way I can just put the images into a folder and have your tool process them instead of attempting to fetch them itself?

**Comment by Niels-IO** [comment]
Hi @mmarseu, 
sorry for the confusion!

> Is there a way I can just put the images into a folder and have your tool process them instead of attempting to fetch them itself?

Yes, this is the main use case actually: You can just put them in the image folder you specify via the next.config.js like this:
`nextImageExportOptimizer_imageFolderPath: "public/images",`
and the tool will automatically optimize these images. I thought you want to do that dynamically using a remote image (which is possible usually).

**Comment by mmarseu** [comment]
Oh, I see. I guess I was so focused on my problem that I lost track of the big picture 😅 
Thank you. That should probably work for me.

**Pull request closed without merging**
